// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoH2b-sywYEoxDipux5f0uHjYXHdKPDzk',
    appId: '1:393598831148:web:a77a90d100eb22212f9f89',
    messagingSenderId: '393598831148',
    projectId: 'medscarrier',
    authDomain: 'medscarrier.firebaseapp.com',
    storageBucket: 'medscarrier.firebasestorage.app',
    measurementId: 'G-3GCDQZLQ16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALdfoa0X8W3myiQ7ez469JClzsBReJOEg',
    appId: '1:393598831148:android:33f11ff3edcf92a82f9f89',
    messagingSenderId: '393598831148',
    projectId: 'medscarrier',
    storageBucket: 'medscarrier.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp2V6Lr_x7iVoYprGoeWFXZNIVdXkL_3o',
    appId: '1:393598831148:ios:993aa3960d68f3282f9f89',
    messagingSenderId: '393598831148',
    projectId: 'medscarrier',
    storageBucket: 'medscarrier.firebasestorage.app',
    iosBundleId: 'com.medscarrier.medscarrier',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp2V6Lr_x7iVoYprGoeWFXZNIVdXkL_3o',
    appId: '1:393598831148:ios:993aa3960d68f3282f9f89',
    messagingSenderId: '393598831148',
    projectId: 'medscarrier',
    storageBucket: 'medscarrier.firebasestorage.app',
    iosBundleId: 'com.medscarrier.medscarrier',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoH2b-sywYEoxDipux5f0uHjYXHdKPDzk',
    appId: '1:393598831148:web:1fc81e315818334c2f9f89',
    messagingSenderId: '393598831148',
    projectId: 'medscarrier',
    authDomain: 'medscarrier.firebaseapp.com',
    storageBucket: 'medscarrier.firebasestorage.app',
    measurementId: 'G-TY7NH5BN2K',
  );
}
